# DO NOT EDIT THIS FILE!
#
# Python module GPS__POA generated by omniidl

import omniORB
omniORB.updateModule("GPS__POA")

# ** 1. Stub files contributing to this module
import GPSData_idl

# ** 2. Sub-modules

# ** 3. End
